apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: "sai-gandikota"
  annotations:
    tcs.net/job-function: engineering
    tcs.net/company: Tata Consultancy Services (TCS)
    tcs.net/github-username: skgandikota
spec:
  profile:
    displayName: Gandikota, Sai
    email: sai.gandikota@mnscorp.net
  memberOf: [guest]
